### ISSUE TITLE
Feature request: Add message if nothing is found in "Existing pathway presentation" search

### ISSUE THREAD

**Issue by khanspers** [jacobwindsor/pathway-presenter#4]
Tried searching for something (before making any presentations) and I get no response. However, would be nice to show a message saying "no results" since otherwise it's not clear if the feature is broken.

**Comment by jacobwindsor** [comment]
Thanks for the feature request :smile:.

This is low priority since that form will not exist past this pre-integration stage.

**Comment by khanspers** [comment]
Right, nevermind. Feel free to close this one.
