### ISSUE TITLE
Large pathways dont load

### ISSUE THREAD

**Issue by khanspers** [jacobwindsor/pathway-presenter#5]
Some large/complicated pathways never finish loading in Pathway Presenter. There is a perpetual loading symbol (tried to catch in screenshot), but the pathways never load. Some to test one:

http://www.wikipathways.org/index.php/Pathway:WP2472
http://www.wikipathways.org/index.php/Pathway:WP706
http://www.wikipathways.org/index.php/Pathway:WP2064 (This one loads, just slower, so might be useful for testing)

<img width="316" alt="screen shot 2017-08-24 at 4 00 23 pm" src="https://user-images.githubusercontent.com/1442197/29692745-86bac794-88e6-11e7-9f5b-638c3a4f24a7.png">

**Comment by jacobwindsor** [comment]
This is a known bug in Pvjs and is not related to the Pathway Presenter. It will be fixed in the next Pvjs release.

For future, all issues that are to do with the actual diagram (currently, there are a fair few) and not the presenter UI belong to Pvjs. 

Closing as not relevant to this repo
